---
- name: Pull myapi image from DockerHub
  docker_image:
    name: ajd2119/tp-devops-myapi
    tag: latest
    source: pull

- name: Run API container
  docker_container:
    name: myapi
    image: ajd2119/tp-devops-myapi:latest
    restart_policy: always
    networks:
      - name: app-network
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://mydatabase:5432/db
      SPRING_DATASOURCE_USERNAME: usr
      SPRING_DATASOURCE_PASSWORD: pwd
    published_ports:
      - "8080:8080"
