# Workflow name
name: CI devops 2025

# Trigger workflow on pushes or PRs to main or develop branches
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  # Job to build and test the backend application
  test-backend:
    runs-on: ubuntu-24.04  # Use Ubuntu runner

    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Java JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Build and test the project using Maven
      - name: Build and test with Maven
        run: mvn -f myapi/pom.xml clean verify

      # Step 4: Run SonarCloud analysis for code quality
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG_KEY }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Token stored in GitHub secrets

  # Job to build and push Docker images; runs only if test-backend succeeds
  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub using GitHub secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build and push backend Docker image
      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./myapi                    # Path to backend Dockerfile
          file: ./myapi/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}  # Only push on main branch
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-myapi:latest

      # Step 4: Build and push database Docker image
      - name: Build and push database image
        uses: docker/build-push-action@v6
        with:
          context: ./mydatabase               # Path to database Dockerfile
          file: ./mydatabase/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}  # Only push on main branch
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-mydatabase:latest

      # Step 5: Build and push HTTP container Docker image
      - name: Build and push http container image
        uses: docker/build-push-action@v6
        with:
          context: ./myhttpcontainer          # Path to HTTP container Dockerfile
          file: ./myhttpcontainer/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}  # Only push on main branch
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-myhttpcontainer:latest
