name: CI devops 2025

on:
  # Trigger the workflow when pushing or creating PRs to main or develop
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test-backend:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Checkout the code from your repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Java JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Build and test with Maven
      - name: Build and test with Maven
        run:  mvn -f myapi/pom.xml clean verify
