name: CI DevOps 2025

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  # ---------- TEST BACKEND ----------
  test-backend:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build, test and analyze with SonarCloud
        run: |
          mvn -B verify sonar:sonar \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=${{ secrets.SONAR_ORG_KEY }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            --file ./myapi/pom.xml

  # ---------- BUILD AND PUSH DOCKER IMAGES ----------
  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./myapi
          file: ./myapi/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-myapi:latest

      - name: Build and push database image
        uses: docker/build-push-action@v6
        with:
          context: ./mydatabase
          file: ./mydatabase/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-mydatabase:latest

      - name: Build and push HTTP container image
        uses: docker/build-push-action@v6
        with:
          context: ./myhttpcontainer
          file: ./myhttpcontainer/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-myhttpcontainer:latest

  # ---------- DEPLOY WITH ANSIBLE ----------
  deploy-to-server:
    needs: build-and-push-docker-image
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python & Ansible
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install ansible

      - name: Add SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Debug SSH key
        run: |
          echo "Verifying SSH key presence..."
          ls -la ~/.ssh
          head -5 ~/.ssh/id_rsa || echo "SSH key missing!"

      - name: Run Ansible playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i ansible-tp/inventories/setup.yml ansible-tp/playbook.yml \
            --private-key ~/.ssh/id_rsa -u admin
